---
synced:
  - host: ../HTRC-Portal
    guest: /htrc/portal
  - host: ../HTRC-IDPAndRegistry
    guest: /htrc/idp
ports:
  - host: 10443
    guest: 10433
  - host: 11443
    guest: 11443
  - host: 18080
    guest: 8080
