---
- name: Run 'yum update'
  yum: name=* state=latest

- name: Add docker repo
  template: src=docker.repo dest=/etc/yum.repos.d/docker.repo

- name: Install docker
  yum: name='docker-engine' state=present

- name: Start docker daemon
  service: name=docker state=started

- name: Setup docker daemon to start at boot
  command: chkconfig docker on

- name: Add 'vagrant' user to docker group
  user: name=vagrant groups=docker append=yes

- include: docker-compose.yml
