---
- name: Add WebUpd8 repo
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: Automatically select the Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: Install Java8
  apt: name=oracle-java8-installer state=present update_cache=yes
